Page({
    data:{
        credentials:[
            {name:'身份证',src:'../../assets/images/hospitalList/header.jpg'},
            {name:'户口本',src:'../../assets/images/hospitalList/header.jpg'},
            {name:'结婚证',src:'../../assets/images/hospitalList/header.jpg'}
        ]
    }
})